[package]
name = "cobble"
version = "0.1.0"
edition = "2024"
description = "Assembler/compiler/interpreter for an 8-bit ISA"
repository = "https://github.com/emil1003/cobble"
license = "MIT"

[dependencies]
clap = { version = "4.5.49", features = ["derive"] }
nom = "8.0.0"
thiserror = "2.0.17"
